# Generated by Django 4.2.13 on 2026-05-01 22:48

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteo',
            name='ajuste_aplicado',
        ),
        migrations.RemoveField(
            model_name='conteodetalle',
            name='cantidad_sistema',
        ),
        migrations.RemoveField(
            model_name='conteodetalle',
            name='diferencia',
        ),
        migrations.AddField(
            model_name='conteo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('conciliado', 'Conciliado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='conteo',
            name='fecha_hora_conteo',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del conteo'),
        ),
        migrations.AddField(
            model_name='conteodetalle',
            name='ajuste_aplicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conteodetalle',
            name='cantidad_sistema_al_conteo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Sistema al conteo'),
        ),
        migrations.AddField(
            model_name='conteodetalle',
            name='diferencia_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Diferencia final'),
        ),
        migrations.AddField(
            model_name='conteodetalle',
            name='diferencia_original',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Diferencia original'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='fecha_movimiento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del movimiento'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha registro'),
        ),
    ]
