# Generated by Django 4.2.13 on 2026-06-23 22:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_inventarioconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='facturas/%Y/%m/')),
                ('tipo_documento', models.CharField(choices=[('factura', 'Factura'), ('envio', 'Envío')], max_length=10)),
                ('numero_documento', models.CharField(blank=True, max_length=60)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('producto', models.CharField(blank=True, choices=[('camiseta', 'Camiseta'), ('lisa', 'Lisa'), ('otro', 'Otro')], max_length=20)),
                ('total_libras', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_por_libra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('isv', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ISV')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('texto_extraido', models.TextField(blank=True)),
                ('estado_revision', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisada', 'Revisada'), ('error', 'Error')], default='pendiente', max_length=12)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='pendiente', max_length=12)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Documento de factura',
                'verbose_name_plural': 'Documentos de factura',
                'ordering': ['-fecha_documento', '-created_at'],
                'permissions': [('ver_facturas', 'Puede ver el módulo de facturas'), ('gestionar_facturas', 'Puede crear y editar documentos de facturas'), ('registrar_pago_factura', 'Puede registrar pagos de facturas'), ('anular_factura', 'Puede anular documentos de facturas'), ('gestionar_tarifas', 'Puede gestionar tarifas de cliente')],
            },
        ),
        migrations.CreateModel(
            name='TarifaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('camiseta', 'Camiseta'), ('lisa', 'Lisa'), ('otro', 'Otro')], max_length=20)),
                ('precio_por_libra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Tarifa de cliente',
                'verbose_name_plural': 'Tarifas de cliente',
                'ordering': ['cliente', 'producto', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('deposito', 'Depósito'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='facturas/pagos/%Y/%m/')),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.documentofactura')),
            ],
            options={
                'verbose_name': 'Pago de factura',
                'verbose_name_plural': 'Pagos de factura',
                'ordering': ['-fecha_pago', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tarifacliente',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('cliente', 'producto'), name='tarifa_unica_activa_por_cliente_producto'),
        ),
    ]
