# Generated by Django 4.2.13 on 2026-06-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_documentofactura_tarifacliente_pagofactura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dias_credito',
            field=models.PositiveIntegerField(default=0, help_text='Días para calcular el vencimiento de facturas y envíos (0 = contado).', verbose_name='Días de crédito'),
        ),
    ]
