# Generated by Django 4.2.13 on 2026-06-28 19:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_metodopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='facturas/pagos/%Y/%m/')),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='core.cliente')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='core.metodopago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AplicacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='core.documentofactura')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='core.pago')),
            ],
            options={
                'verbose_name': 'Aplicación de pago',
                'verbose_name_plural': 'Aplicaciones de pago',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='aplicacionpago',
            constraint=models.CheckConstraint(check=models.Q(('monto__gt', 0)), name='aplicacion_monto_positivo'),
        ),
    ]
