# Generated by Django 4.2.13 on 2026-06-30 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_migrar_pagos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagoFactura',
        ),
    ]
