# Generated by Django 4.2.13 on 2026-07-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_delete_pagofactura'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('palabra_clave', models.CharField(blank=True, help_text='Si el nombre del archivo la contiene, el envío se clasifica en esta categoría.', max_length=60)),
                ('es_predeterminada', models.BooleanField(default=False, help_text='Categoría asignada cuando ninguna palabra clave coincide.')),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de producto',
                'ordering': ['orden', 'nombre'],
                'permissions': [('gestionar_categorias_producto', 'Puede gestionar categorías de producto')],
            },
        ),
    ]
