# Generated by Django 4.2.13 on 2026-07-01 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_categoriaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofactura',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='core.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='tarifacliente',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='core.categoriaproducto'),
        ),
    ]
