# Generated by Django 4.2.13 on 2026-07-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_sembrar_y_migrar_categorias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifacliente',
            options={'ordering': ['cliente', 'categoria', '-fecha_inicio'], 'verbose_name': 'Tarifa de cliente', 'verbose_name_plural': 'Tarifas de cliente'},
        ),
        migrations.RemoveConstraint(
            model_name='tarifacliente',
            name='tarifa_unica_activa_por_cliente_producto',
        ),
        migrations.AlterField(
            model_name='tarifacliente',
            name='producto',
            field=models.CharField(blank=True, choices=[('camiseta', 'Camiseta'), ('lisa', 'Lisa'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='tarifacliente',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('cliente', 'categoria'), name='tarifa_unica_activa_por_cliente_categoria'),
        ),
    ]
