# Generated by Django 4.2.13 on 2026-07-02 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_tarifacliente_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentofactura',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='tarifacliente',
            name='producto',
        ),
    ]
