# Generated by Django 4.2.13 on 2026-07-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_tarifacliente_categoria_no_nula'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='color',
            field=models.CharField(blank=True, help_text='Color hex (p. ej. #FFA500) para resaltar la categoría en el estado de cuenta.', max_length=7),
        ),
        migrations.AddField(
            model_name='documentofactura',
            name='subcliente',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
