# Generated by Django 4.2.30 on 2026-07-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_categoriaproducto_color_documentofactura_subcliente'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(check=models.Q(('monto__gt', 0)), name='pago_monto_positivo'),
        ),
    ]
