# Generated by Django 4.2.30 on 2026-07-24 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_pago_pago_monto_positivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('alias_norm', models.CharField(db_index=True, editable=False, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Alias de cliente',
                'verbose_name_plural': 'Alias de cliente',
                'ordering': ['alias'],
            },
        ),
        migrations.AddConstraint(
            model_name='clientealias',
            constraint=models.UniqueConstraint(fields=('alias_norm',), name='cliente_alias_norm_unico'),
        ),
    ]
