# Generated by Django 4.2.30 on 2026-07-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_clientealias'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofactura',
            name='cliente_sugerido',
            field=models.CharField(blank=True, help_text='Nombre del cliente que venía en el archivo cuando la ingesta automática no pudo emparejarlo.', max_length=200),
        ),
    ]
