# Generated by Django 4.2.30 on 2026-08-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_backfill_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofactura',
            name='tipo_documento',
            field=models.CharField(choices=[('factura', 'Factura'), ('envio', 'Envío'), ('apertura', 'Saldo inicial')], max_length=10),
        ),
    ]
